### ISSUE TITLE
Improved support for updating existing collections [Feature request/suggestion]

### ISSUE THREAD

**Issue by lionslancer** [Ajatt-Tools/PitchAccent#1]
Given that a majority of people using this fork are probably using the Yomichan + mpvacious (or similar) method for mining new cards, I think it would be a good idea to make it as easy as possible for them to update their existing collections to a similar format.

The way I see it, the main advantages that Yomichan has over this add-on right now are the following:
- In cases where there are multiple possible readings, the correct one will always be used since the user chooses which entry to base the new card on.
- It can output the pitch accent number, making pitch coloring via CSS very simple.

As a base example of the potential problem with multiple readings, if a lookup was performed on a card with "足" in the target field, the previous version of this add-on would always generate the pitch accent pattern for あし , even if the intended reading was そく. The current version will instead generate readings for both. 

This presents a problem when updating cards in bulk, since it would not be possible to ensure that every card had the accent generated for the correct reading. One way of avoiding this problem could by looking at existing furigana (using square bracket syntax) when performing lookups. 

I'm not sure how much of this is feasible with the current backend (such as whether or not pitch numbering is supported), but it may be worth looking at switching over to Kanjium long-term, as that seems to be new standard choice, in order to maintain parity with Yomichan (and other applications) going forward.

Personally, I'm mainly interested in converting an old deck that was created using the MIA/Migaku pitch accent add-on to a more compatible format, while maintaining pitch accent coloring. Given that Migaku's syntax isn't compatible with anything else, this more or less necessitates regenerating accents for every card. I can only assume that I'm not the only one with this problem. I think the entire community would benefit from having a standard syntax for pitch accent information, and going by pitch number seems to me like the best candidate.

**Comment by tatsumoto-ren** [comment]
*Please don't use GitHub to discuss issues related to AJT projects.*

The purpose of this add-on is to add readings at times when Yomichan fails to do so. If we switch to kanjium, this add-on will become useless because it would provide the same information Yomichan does. I think it would be nice to **add** kanjium data to the existing data, but replacing it is a regression. A new parser should be written to convert kanjium data to the format we use now, but it shouldn't be too hard. Also note that kanjium data doesn't provide any information about de-voiced vowels and nasal sounds. 

> output the pitch accent number

I think this functionality could be added. It's just a matter of implementing more parsing. 

>  The current version will instead generate readings for both.

Are you sure? The csv file we use to generate readings doesn't provide multiple entries for 足, and when I try it on my machine I only get one reading. I don't think it's correct to have そく as a standalone word. See the screenshot.

![screenshot-2021-08-09-09-27-50](https://user-images.githubusercontent.com/69171671/128687758-74b2ebb7-7c06-4736-99c1-1151c57577a4.png)

>  looking at existing furigana 

This is a valid solution when using bulk-add and when updating notes added by yomichan, but it's going to fail when you add notes by hand because there's no way to guarantee which add-on is going to fire first, this one or "Japanese support" which is responsible for generating readings.

I think the best way to tackle this is to let the user switch `srcField` from `VocabKanji` to `VocabFurigana` and make the add-on detect it.

> whether or not pitch numbering is supported

You can calculate pitch number if you look at the last field of the `ACCDB_unicode.csv` file. After that you can save it as a new field to `nhk_pronunciation.csv`.

> pitch accent coloring

I have never used any of the m**aku add-ons so I'm not very familiar with how they work, but if pitch accent coloring is something people want, I think it would be nice to make a new add-on just for that. I'm not sure if coloring is useful though. It was invented by mattvsjapan under the pretext that it aids memorization, but there's no proof that it actually helps you remember pitch accents of individual words.

> syntax

In my opinion, the best way to go about syntax is to use HTML tags, e.g.: `<span class="heiban nakadaka" accents="0 2">物量</span>`. It's going to be easy to parse and edit by hand, and nothing will break if you don't have these classes specified in your note type.

**Comment by tatsumoto-ren** [comment]
Having said that, depending on the amount of donations this project receives, I might be able to develop it in a relatively short period of time.

**Comment by lionslancer** [comment]
> _Please don't use GitHub to discuss issues related to AJT projects._

Noted. I take that means Matrix for discussion and GitHub for PRs in the future?
<br>

> A new parser should be written to convert kanjium data to the format we use now.

The only thing that sticks out to me about this is that cards will look different depending on how they were generated. 
<br>

> The csv file we use to generate readings doesn't provide multiple entries for 足

I had furigana in the source field for testing. Most likely it triggered a separate kana lookup.
<br>

> I don't think it's correct to have そく as a standalone word. See the screenshot.

In this case it was そく as counter for socks, etc.
<br>

> I think the best way to tackle this is to let the user switch `srcField` from `VocabKanji` to `VocabFurigana` and make the add-on detect it.

Configuring `srcField` separately for bulk-add and adding new notes would make it set-and-forget.
<br>

> You can calculate pitch number if you look at the last field of the `ACCDB_unicode.csv` file. After that you can save it as a new field to `nhk_pronunciation.csv`.

Thanks, I'll take a look at if I have time. I'll submit a PR if I come up with something useful. I'll go ahead and close this now.

**Comment by tatsumoto-ren** [comment]
> Matrix for discussion and GitHub for PRs in the future?

Preferably, yes.

> cards will look different depending on how they were generated

Pitch accent graphs will be slightly different, but they are different as of today too if you compare what yomichan generates and what this addon generates.

> I had furigana in the source field for testing. Most likely it triggered a separate kana lookup.

Makes sense. The goal for the next release should be to teach the add-on to distinguish furigana.

> Configuring srcField separately for bulk-add and adding new notes would make it set-and-forget.

Currently, there's only one setting for srcField. Are you suggesting that there should be two? I think it makes sense to let the user choose when bulk-generating, but default to what is specified in the config when adding cards normally.

> I'll submit a PR if I come up with something useful.

Alright. Note that the notation used in `ACCDB_unicode.csv` is pretty different from what you usually see, and it has many exception cases that have to be taken into account.

**Comment by lionslancer** [comment]
> Currently, there's only one setting for srcField. Are you suggesting that there should be two?

A separate setting is one way to account for different behavior during bulk-generation. Letting the user choose is a better solution to the same problem.

**Comment by tatsumoto-ren** [comment]
Added furigana-aware lookups in the latest release. If you have `VocabFurigana` filled and press tab, it will use it to generate pitch accents for the right reading. 

The next step is to add source and destination field selector to the bulk-add menu.
